/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphdynamicplotting;
import javax.swing.*;
/**
 *
 * @author Fahim
 */
public class SensorWindow extends javax.swing.JFrame {

    /**
     * Creates new form SensorWindow
     */
    public SensorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tempButton = new javax.swing.JButton();
        airQualityButton = new javax.swing.JButton();
        flameButton = new javax.swing.JButton();
        liquidLeakButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempButton.setText("Temperature/Humidity Sensor");
        tempButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempButtonActionPerformed(evt);
            }
        });

        airQualityButton.setText("Air Quality Sensor");
        airQualityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airQualityButtonActionPerformed(evt);
            }
        });

        flameButton.setText("Flame Sensor");
        flameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flameButtonActionPerformed(evt);
            }
        });

        liquidLeakButton.setText("Liquid Leakage Sensor");
        liquidLeakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquidLeakButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airQualityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liquidLeakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airQualityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liquidLeakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
            dispose();
        
        
    }                                          

    private void airQualityButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
                JFrame frame = new JFrame ("Air Quality Chart");
                AirQualitySensorChart rtcp = new AirQualitySensorChart ("Air Quality Data", "Sensor Reading", "value");
                frame.getContentPane (). add (rtcp, new java.awt.BorderLayout(). CENTER);
                frame.pack ();
                frame.setVisible (true);
                new Thread(rtcp).start();
                frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
                
    }                                                

    private void tempButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
                JFrame frame = new JFrame ("Temperature/Humidity Chart");
                TemperatureHumiditySensorChart rtcp = new TemperatureHumiditySensorChart ("Temperature Data", "Sensor Reading", "value");
                frame.getContentPane (). add (rtcp, new java.awt.BorderLayout(). CENTER);
                frame.pack ();
                frame.setVisible (true);
                new Thread(rtcp).start();
                frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }                                          

    private void flameButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
                JFrame frame = new JFrame ("Flame Detection Chart");
                FlameSensorChart rtcp = new FlameSensorChart ("Flame Sensor Data", "Sensor Reading", "value");
                frame.getContentPane (). add (rtcp, new java.awt.BorderLayout(). CENTER);
                frame.pack ();
                frame.setVisible (true);
                new Thread(rtcp).start();
                frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }                                           

    private void liquidLeakButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
                JFrame frame = new JFrame ("Liquid Leakage Chart");
                LiquidLeakageSensorChart rtcp = new LiquidLeakageSensorChart ("Liquid Detection Sensor Data", "Sensor Reading", "value");
                frame.getContentPane (). add (rtcp, new java.awt.BorderLayout(). CENTER);
                frame.pack ();
                frame.setVisible (true);
                new Thread(rtcp).start();
                frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SensorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SensorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SensorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SensorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SensorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton airQualityButton;
    private javax.swing.JButton flameButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton liquidLeakButton;
    private javax.swing.JButton tempButton;
    // End of variables declaration                   
}
